DROP TABLE IF EXISTS GROUPS CASCADE;

CREATE TABLE IF NOT EXISTS GROUPS
(
	ID INTEGER NOT NULL,
	Name character(6) COLLATE pg_catalog.default NOT NULL,
		CONSTRAINT GROUPS_pkey PRIMARY KEY (ID)
	)

	TABLESPACE pg_default;

	ALTER TABLE IF EXISTS GROUPS
    	OWNER to "Admin";