DROP TABLE IF EXISTS LECTURERS CASCADE;

CREATE TABLE IF NOT EXISTS LECTURERS
(
	ID INTEGER NOT NULL,
	First_Name CHARACTER(10)  NOT NULL,
	Last_Name CHARACTER(10) NOT NULL,
	Course_ID INTEGER,
    User_ID INTEGER,
	CONSTRAINT "lECTURER_pkey" PRIMARY KEY (ID)
)

	TABLESPACE pg_default;

	ALTER TABLE IF EXISTS LECTURERS
   		OWNER to "Admin";