DROP TABLE IF EXISTS LECTURES CASCADE;

CREATE TABLE IF NOT EXISTS LECTURES
(
ID INTEGER NOT NULL PRIMARY KEY,
Day_Number INTEGER NOT NULL,
Pair INTEGER NOT NULL,
Start CHARACTER(5) NOT NULL,
End_Time CHARACTER(5) NOT NULL,
Day CHARACTER(10) NOT NULL,
Course INTEGER NOT NULL,
FOREIGN KEY (Course) REFERENCES COURSES (ID) ON DELETE CASCADE
)
	
	TABLESPACE pg_default;

	ALTER TABLE IF EXISTS LECTURES
    	OWNER to "Admin";