DROP TABLE IF EXISTS LECTUREGROUP CASCADE;

CREATE TABLE IF NOT EXISTS LECTUREGROUP
(
	Group_ID INTEGER NOT NULL REFERENCES GROUPS,
	Lecture_ID INTEGER NOT NULL REFERENCES LECTURES
)

	TABLESPACE pg_default;

	ALTER TABLE IF EXISTS LECTUREGROUP
   		OWNER to "Admin";