DROP TABLE IF EXISTS USERS CASCADE;

CREATE TABLE IF NOT EXISTS USERS
(
    ID INTEGER NOT NULL,
    Login CHARACTER(8) UNIQUE,
    Password CHARACTER(60),
    User_role CHARACTER(10),
    CONSTRAINT USERS_pkey PRIMARY KEY (ID)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS STUDENTS
    OWNER to "Admin";