DROP TABLE IF EXISTS STAFF CASCADE;

CREATE TABLE IF NOT EXISTS STAFF
(
    ID INTEGER NOT NULL,
    First_Name CHARACTER(10)  NOT NULL,
    Last_Name CHARACTER(10) NOT NULL,
    Position CHARACTER(20) NOT NULL,
    User_ID integer REFERENCES USERS(ID),
    CONSTRAINT "STAFF_pkey" PRIMARY KEY (ID)
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS STAFF
    OWNER to "Admin";