DROP TABLE IF EXISTS GROUPS_COURSES_RELATIONS CASCADE;

CREATE TABLE IF NOT EXISTS GROUPS_COURSES_RELATIONS
(
    Group_ID INTEGER REFERENCES GROUPS(ID),
    Course_ID INTEGER REFERENCES COURSES(ID)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS GROUPS_COURSES_RELATIONS
    OWNER to "Admin";